//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KSPPartRemover.Tests.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("KSPPartRemover.Tests.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pid = 5bc46e52b7ff47b2b04dc6227e47264f
        ///name = Far Point Station
        ///type = Station
        ///sit = ORBITING
        ///landed = False
        ///landedAt = 
        ///splashed = False
        ///met = 324133660.270204
        ///lct = 25767.0013672735
        ///root = 0
        ///lat = 0.627136213369342
        ///lon = -131.103962479068
        ///alt = 663518.211975401
        ///hgt = -1
        ///nrm = -0.2275127,0.9460879,-0.2305554
        ///rot = 0.6855445,-0.3821644,0.1198651,-0.6079569
        ///CoM = -2.484447,13.99407,-0.7855127
        ///stg = 3
        ///prst = False
        ///ref = 3032554701
        ///ctrl = True
        ///cPch = -0.128
        ///cHdg = -4.106
        ///cMod = 0
        ///ORBIT        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _5bc46e52_b7ff_47b2_b04d_c6227e47264f_expected {
            get {
                return ResourceManager.GetString("_5bc46e52_b7ff_47b2_b04d_c6227e47264f_expected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pid = 5bc46e52b7ff47b2b04dc6227e47264f
        ///name = Far Point Station
        ///type = Station
        ///sit = ORBITING
        ///landed = False
        ///landedAt = 
        ///splashed = False
        ///met = 324133660.270204
        ///lct = 25767.0013672735
        ///root = 0
        ///lat = 0.627136213369342
        ///lon = -131.103962479068
        ///alt = 663518.211975401
        ///hgt = -1
        ///nrm = -0.2275127,0.9460879,-0.2305554
        ///rot = 0.6855445,-0.3821644,0.1198651,-0.6079569
        ///CoM = -2.484447,13.99407,-0.7855127
        ///stg = 3
        ///prst = False
        ///ref = 3032554701
        ///ctrl = True
        ///cPch = -0.128
        ///cHdg = -4.106
        ///cMod = 0
        ///ORBIT        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _5bc46e52_b7ff_47b2_b04d_c6227e47264f_in {
            get {
                return ResourceManager.GetString("_5bc46e52_b7ff_47b2_b04d_c6227e47264f_in", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ship = Mün Mk I
        ///version = 0.23.5
        ///description = 
        ///type = VAB
        ///PART
        ///{
        ///	part = fuelTank_4294291662
        ///	partName = Part
        ///	pos = -0.2561799,3.782969,0.2440315
        ///	rot = 0,0,0,1
        ///	attRot = 0,0,0,1
        ///	mir = 1,1,1
        ///	istg = 0
        ///	dstg = 0
        ///	sidx = -1
        ///	sqor = -1
        ///	attm = 0
        ///	link = fuelTank_4294291630
        ///	link = liquidEngine_4294290234
        ///	attN = top,fuelTank_4294291630
        ///	attN = bottom,liquidEngine_4294290234
        ///	EVENTS
        ///	{
        ///	}
        ///	ACTIONS
        ///	{
        ///	}
        ///	RESOURCE
        ///	{
        ///		name = LiquidFuel
        ///		amount = 180
        ///		maxAmount = 180
        ///		flowSt [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Mün_Mk_I_expected_craft {
            get {
                return ResourceManager.GetString("Mün_Mk_I_expected_craft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ship = Mün Mk I
        ///version = 0.23.5
        ///description = 
        ///type = VAB
        ///PART
        ///{
        ///	part = fuelTank_4294291662
        ///	partName = Part
        ///	pos = -0.2561799,3.782969,0.2440315
        ///	rot = 0,0,0,1
        ///	attRot = 0,0,0,1
        ///	mir = 1,1,1
        ///	istg = 0
        ///	dstg = 0
        ///	sidx = -1
        ///	sqor = -1
        ///	attm = 0
        ///	link = fuelTank_4294291630
        ///	link = liquidEngine_4294290234
        ///	attN = top,fuelTank_4294291630
        ///	attN = bottom,liquidEngine_4294290234
        ///	EVENTS
        ///	{
        ///	}
        ///	ACTIONS
        ///	{
        ///	}
        ///	RESOURCE
        ///	{
        ///		name = LiquidFuel
        ///		amount = 180
        ///		maxAmount = 180
        ///		flowSt [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Mün_Mk_I_in_craft {
            get {
                return ResourceManager.GetString("Mün_Mk_I_in_craft", resourceCulture);
            }
        }
    }
}
